/** Khmer UI strings — Data Visualize (indicator explorer) */
export const VIZ_KH = {
  pageTitle: 'ការបង្ហាញទិន្នន័យជាក្រាហ្វិក',
  pageTitleEventReport: 'របាយការណ៍ព្រឹត្តិការណ៍',
  pageDescription: 'ឧបករណ៍រុករកសូចនាករ និងទិន្នន័យសុខាភិបាល',
  navEventReport: 'ព្រឹត្តិការណ៍',
  navEventReportTitle: 'របាយការណ៍ព្រឹត្តិការណ៍ — ជ្រើសព្រឹត្តិការណ៍ រយៈពេល និងដំណើរការ',
  facility: 'មូលដ្ឋានសុខាភិបាល',
  scopeRollup: 'ទិន្នន័យបូកសរុប',
  scopeRollupShort: 'សរុប',
  scopeCompare: 'ប្រៀបធៀប',
  scopeRollupHint: 'ថ្នាក់ខេត្ត / ថ្នាក់ជាតិ / មូលដ្ឋានសុខាភិបាល',
  scopeModeLabel: 'របៀបបង្ហាញទិន្នន័យ',
  resultViewLabel: 'របៀបមើលលទ្ធផល',
  copyClipboard: 'ចម្លង',
  copyClipboardTitle: 'ចម្លងទិន្នន័យទៅក្ដារតម្បៀត (Excel)',
  copyClipboardSuccess: 'បានចម្លងទៅក្ដារតម្បៀតហើយ',
  copyClipboardFailed: 'មិនអាចចម្លងបានទេ',
  copyClipboardEmpty: 'មិនមានទិន្នន័យចម្លង',
  indicatorsShort: 'សូចនាករ',
  scopeCompareHint: 'មូលដ្ឋានសុខាភិបាលច្រើន',
  siteModal: {
    selectPlaceholder: 'ជ្រើសរើសទិន្នន័យបូកសរុប…',
    titleFacility: 'ជ្រើសរើសកម្រិតទិន្នន័យបូកសរុប (ខេត្ត / ជាតិ / មូលដ្ឋាន)',
    hintFacility: 'ជ្រើសរើសខេត្ត ប្រទេស ឬមូលដ្ឋានសុខាភិបាលមួយ — លទ្ធផលនឹងបូកសរុបពីមូលដ្ឋានថ្នាក់ក្រោម។',
    titleSite: 'ជ្រើសរើសទីតាំងបូកសរុប',
    hintSite: 'ជ្រើសរើសខេត្ត ប្រទេស ឬមូលដ្ឋានសុខាភិបាល។',
    filterPlaceholder: 'ស្វែងរក…',
    cancel: 'បោះបង់',
    apply: 'អនុវត្ត'
  },
  compareModal: {
    selectPlaceholder: 'ជ្រើសរើសមូលដ្ឋានដើម្បីប្រៀបធៀប…',
    title: 'ប្រៀបធៀបមូលដ្ឋានសុខាភិបាល (ច្រើន)',
    hint: 'ជ្រើសរើសតាមកម្ពុជា ខេត្ត ឬមូលដ្ឋាន — ចុចឈ្មោះខេត្តដើម្បីមើលមូលដ្ឋាន។',
    hintProvince: 'ជ្រើសរើសខេត្ត — ចុចឈ្មោះខេត្តដើម្បីមើលមូលដ្ឋាន (អតិបរមា ៨០)។',
    filterPlaceholder: 'ស្វែងរកខេត្ត ឬមូលដ្ឋានសុខាភិបាល…',
    selectionLevelLabel: 'កម្រិតជ្រើសរើស',
    selectionLevelFacility: 'មូលដ្ឋាន',
    selectionLevelProvince: 'ខេត្ត',
    selectProvinceHint: 'ជ្រើសរើស/លុបខេត្ត',
    expandProvinceHint: 'បង្ហាញ/លាក់មូលដ្ឋានក្នុងខេត្ត',
    viewFacilitiesHint: 'មើលមូលដ្ឋាន (ជ្រើសរើសតាមខេត្ត)',
    selectCambodiaHint: 'ជ្រើសរើសមូលដ្ឋានទាំងអស់ក្នុងកម្ពុជា (អតិបរមា ៨០)',
    selectAllProvincesHint: 'ជ្រើសរើសខេត្តទាំងអស់ក្នុងកម្ពុជា',
    selectAllCambodia: 'ជ្រើសរើសទាំងកម្ពុជា',
    selectAllVisible: 'ជ្រើសរើសដែលបង្ហាញ',
    cambodia: 'កម្ពុជា',
    sitesSelected: 'មូលដ្ឋានសុខាភិបាលដែលបានជ្រើសរើស',
    provincesSelected: 'ខេត្តដែលបានជ្រើសរើស',
    cancel: 'បោះបង់',
    apply: 'អនុវត្ត'
  },
  facilityColumn: 'មូលដ្ឋានសុខាភិបាល',
  scopeColumn: 'វិសាលភាព/កម្រិតទិន្នន័យ',
  chartCompareFacilities: 'ប្រៀបធៀបមូលដ្ឋានសុខាភិបាល',
  chartCompareSitesIndicators: 'ប្រៀបធៀបមូលដ្ឋាន × សូចនាករ (ខ្សែ = មូលដ្ឋាន)',
  pickIndicators: 'សូចនាករ',
  pickEvents: 'ព្រឹត្តិការណ៍',
  pickerModeEvents: 'ព្រឹត្តិការណ៍',
  pickerModeAll: 'សូចនាករទាំងអស់',
  modalEventsTitle: 'ជ្រើសរើសព្រឹត្តិការណ៍',
  modalEventsHint: 'ជ្រើសរើសព្រឹត្តិការណ៍គ្លីនិក — មិនបង្ហាញតារាងមូលទិន្នន័យឡើយ',
  searchEvents: 'ស្វែងរកព្រឹត្តិការណ៍…',
  programAll: 'ទាំងអស់',
  programArt: 'មនុស្សពេញវ័យ / កុមារ ART',
  programInfant: 'ទារក EID',
  programPntt: 'តម្រុយ (PNTT)',
  programFilterHint: 'ជ្រើសរើសតាមប្រភេទរបាយការណ៍',
  pickPeriods: 'រយៈពេល',
  pickPeriodsHint: 'ជ្រើសរើសត្រីមាស ខែ ឬឆ្នាំ ដើម្បីប្រៀបធៀបលទ្ធផល។',
  periodKindQuarter: 'ត្រីមាស',
  periodKindMonth: 'ខែ',
  periodKindYear: 'ឆ្នាំ',
  periodModal: {
    selectPlaceholder: 'ជ្រើសរើសរយៈពេល…',
    title: 'ជ្រើសរើសរយៈពេល',
    hint: 'រុករកតាមឆ្នាំ រួចជ្រើសរើសត្រីមាស ខែ ឬឆ្នាំទាំងមូល (អាចជ្រើសរើសបានច្រើន)។',
    browseYear: 'ឆ្នាំ',
    allYearsHint: 'ជ្រើសរើសឆ្នាំទាំងមូល (អាចជ្រើសរើសបានច្រើន)។',
    prevYear: 'ឆ្នាំមុន',
    nextYear: 'ឆ្នាំបន្ទាប់',
    draft: 'ជម្រើស៖',
    cancel: 'បោះបង់',
    apply: 'អនុវត្ត'
  },
  run: 'ដំណើរការ',
  running: 'កំពុងដំណើរការ…',
  refresh: 'ធ្វើឲ្យស្រស់/ដំណើរការឡើងវិញ',
  progress: 'វឌ្ឍនភាព',
  selectedIndicators: 'សូចនាករដែលបានជ្រើសរើស',
  selectedPeriods: 'រយៈពេលដែលបានជ្រើសរើស',
  chart: 'គំនូសតាង/ក្រាហ្វ',
  table: 'តារាងលម្អិត',
  empty: 'សូមជ្រើសរើសមូលដ្ឋាន សូចនាករ និងរយៈពេល រួចចុចប៊ូតុង "ដំណើរការ"។',
  noResults: 'មិនមានលទ្ធផលទិន្នន័យទេ។',
  total: 'សរុប',
  male014: 'ប្រុស ≤ ១៤ ឆ្នាំ',
  female014: 'ស្រី ≤ ១៤ ឆ្នាំ',
  maleOver14: 'ប្រុស ១៥ ឆ្នាំឡើង',
  femaleOver14: 'ស្រី ១៥ ឆ្នាំឡើង',
  age014: '≤ ១៤ ឆ្នាំ',
  age15plus: '១៥ ឆ្នាំឡើង',
  period: '',
  indicator: 'សូចនាករ',
  error: 'កំហុស',
  modalIndicatorsTitle: 'ជ្រើសរើសសូចនាករ',
  modalPeriodsTitle: 'ជ្រើសរើសត្រីមាស',
  modalApply: 'អនុវត្ត',
  modalCancel: 'បោះបង់',
  modalSelectAll: 'ជ្រើសរើសទាំងអស់',
  modalClear: 'សម្អាត',
  pickerQuickPresets: 'ជម្រើសរហ័ស',
  pickerSelectGroup: 'ជ្រើសក្រុមនេះ',
  pickerClearGroup: 'ដកក្រុមនេះ',
  pickerGroupSelected: 'ជ្រើស {n}/{total}',
  pickerNoMatch: 'មិនមានលទ្ធផល — ផ្លាស់ប្តូរការស្វែងរក ឬតម្រង',
  presetVl: 'VL / EAC',
  presetRetention: 'ការបន្តការព្យាបាល (Retention)',
  presetQuality: 'គុណភាព 10.x',
  searchIndicators: 'ស្វែងរកសូចនាករ…',
  viewChart: 'បង្ហាញជាគំនូសតាង',
  viewTable: 'បង្ហាញជាតារាង',
  viewChartShort: 'គំនូសតាង',
  viewTableShort: 'តារាង',
  chartTrendShort: 'និន្នាការ',
  chartSnapshotShort: 'បច្ចុប្បន្ន',
  chartDemographicsShort: 'ប្រជាសាស្ត្រ',
  chartControls: 'ផ្ទាំងបញ្ជាគំនូសតាង',
  chartPickIndicators: 'ជ្រើសរើសសូចនាករលើគំនូសតាង',
  chartOneIndicator: 'សូចនាករមួយ',
  chartNIndicators: 'សូចនាករ {n}',
  chartPickOne: 'ត្រូវជ្រើសរើសសូចនាករយ៉ាងហោចណាស់មួយ',
  chartSeriesMax: 'អាចបង្ហាញលើគំនូសតាងបានរហូតដល់ {n} សូចនាករ',
  chartPickOneHint: 'ជ្រើសរើសយកមួយសម្រាប់បង្ហាញទិន្នន័យប្រជាសាស្ត្រ',
  chartPickManyHint: 'ធីកជ្រើសរើសដើម្បីបង្ហាញលើគំនូសតាង (អតិបរមា {n})',
  chartSelectedOrder: 'លំដាប់លើគំនូសតាង (អូសដើម្បីប្តូរ)',
  chartAddIndicators: 'បន្ថែមសូចនាករ',
  chartCompareMulti: 'ប្រៀបធៀបសូចនាករដែលបានជ្រើសរើស',
  chartSettings: 'ការកំណត់គំនូសតាង',
  chartSettingsTitle: 'ពណ៌ និង ជម្រើសគំនូសតាង',
  chartOptionsSection: 'ជម្រើសគំនូសតាង',
  chartDisplaySection: 'ការបង្ហាញ',
  chartTextSection: 'អក្សរ',
  chartFontSize: 'ទំហំអក្សរ',
  chartFontWeight: 'ក្រាស់អក្សរ',
  chartFontNormal: 'ធម្មតា',
  chartFontMedium: 'មធ្យម',
  chartFontBold: 'ដិត',
  chartColorsSection: 'ពណ៌',
  chartColorByIndicator: 'មូលដ្ឋានមួយ — ពណ៌តាមសូចនាករ',
  chartColorByFacility: 'ប្រៀបធៀបមូលដ្ឋាន — ពណ៌តាមមូលដ្ឋាន',
  chartType: '',
  chartBarShort: 'ជួរឈរ',
  chartLineShort: 'ខ្សែ',
  chartTypeSelect: '',
  chartType_bar: 'ជួរឈរ (Bar)',
  chartType_line: 'ខ្សែ (Line)',
  chartType_area: 'ផ្ទៃ (Area)',
  chartType_stacked: 'ជួរឈរជាន់ (Stacked)',
  chartType_horizontal: 'ជួរឈរផ្ដេក (Horizontal)',
  chartType_pie: 'គំនូសតាងជរុង (Pie)',
  chartPiePeriodHint: 'ត្រីមាសចុងក្រោយ — {period}',
  chartPieNoData: 'មិនមានតម្លៃសម្រាប់គំនូសតាងជរុងឡើយ។',
  chartXLabels: 'ស្លាកអ័ក្ស X',
  chartXLabelsAuto: 'ស្វ័យប្រវត្តិ',
  chartXLabelsStraight: 'ផ្ដេក (រក្សាទាំងអស់)',
  chartXLabelsSlanted: 'ទ្បេក',
  chartBarWidth: 'កម្រិតជួរឈរ',
  chartBarNarrow: 'តូច',
  chartBarMedium: 'មធ្យម',
  chartBarWide: 'ធំ',
  chartLineCurve: 'រូបរាងខ្សែ',
  chartCurveSmooth: 'រលូន',
  chartCurveLinear: 'ត្រង់',
  chartCurveStep: 'ជំហាន',
  chartColorPalette: 'ឈុតពណ៌',
  chartPalette_default: 'លំនាំដើម',
  chartPalette_warm: 'ក្តៅ',
  chartPalette_cool: 'ត្រជាក់',
  chartPalette_pastel: 'ពណ៌ផ្សេង',
  chartPalette_vivid: 'ភ្លឺ',
  chartSeriesColors: 'ពណ៌តាមស៊េរី',
  chartPickColor: 'ជ្រើសរើសពណ៌',
  chartResetColors: 'កំណត់ពណ៌ឡើងវិញ',
  chartResetOneColor: 'លុបពណ៌ផ្ទាល់',
  chartYAxis: 'អ័ក្ស Y',
  chartYFromZero: 'ចាប់ផ្តើមពី ០',
  chartYMax: 'តម្លៃអតិបរមា',
  chartYMaxAuto: 'ស្វ័យប្រវត្តិ',
  chartYMaxManual: 'កំណត់ផ្ទាល់ខ្លួន',
  chartYTicks: 'ចន្លោះដាច់ៗនៃអ័ក្ស',
  chartShowGrid: 'បង្ហាញខ្សែក្រឡាចត្រង្គ',
  chartShowLabels: 'បង្ហាញស្លាកលេខលើជួរឈរ (Data Labels)',
  chartShowLegend: 'បង្ហាញសញ្ញាសម្គាល់ពណ៌ (Legend)',
  chartTooltipHover: 'ប្រអប់ព័ត៌មាន (Hover)',
  chartTooltipSingle: 'មួយស៊េរី',
  chartTooltipAll: 'ទាំងអស់តាមរយៈពេល',
  chartTrend: 'ខ្សែនិន្នាការ',
  chartSnapshot: 'ត្រីមាសចុងក្រោយ',
  chartDemographics: 'ប្រជាសាស្ត្រ',
  chartBar: 'គំនូសតាងជួរឈរ (Bar Chart)',
  chartLine: 'គំនូសតាងខ្សែ (Line Chart)',
  chartTrendLine: 'ខ្សែនិន្នាការ',
  chartTrendLineHint: 'បង្ហាញខ្សែប៉ារឡែល (linear trend) លើគំនូសតាង',
  chartShowTrendLine: 'បង្ហាញខ្សែនិន្នាការ (Trend line)',
  chartBaseline: 'ត្រីមាសដំបូង (Baseline)',
  chartSnapshotHint: 'សរុបតាមសូចនាករ — {period}',
  chartSnapshotCompareGrouped: 'ប្រៀបធៀបមូលដ្ឋានសុខាភិបាល — {period}',
  chartDemographicsHint: '',
  chartNoCompare: 'មិនមានទិន្នន័យគ្រប់គ្រាន់សម្រាប់បង្កើតគំនូសតាងប្រៀបធៀបទេ។',
  chartNoSnapshot: 'មិនមានទិន្នន័យសរុបសម្រាប់ត្រីមាសចុងក្រោយឡើយ។',
  chartNoDemographics: 'សូចនាករនេះមិនមានទិន្នន័យប្រជាសាស្ត្រ (ភេទ/អាយុ) ទេ។',
  chartDetailTitle: 'ព័ត៌មានលម្អិត',
  chartDetailClose: 'បិទ',
  chartClickDetailHint: 'ចុចគំនូសតាងដើម្បីមើលព័ត៌មានលម្អិត',
  chartDetailPatients: 'បញ្ជីអ្នកជំងឺ (កំណត់ត្រា)',
  chartDetailRecordCount: 'កំណត់ត្រា',
  chartDetailLoading: 'កំពុងផ្ទុកបញ្ជីអ្នកជំងឺ…',
  chartDetailNoPatients: 'មិនមានកំណត់ត្រាអ្នកជំងឺ',
  chartDetailNoDrilldown: 'សូចនាករនេះមិនមានបញ្ជីអ្នកជំងឺលម្អិត',
  chartDetailLoadFailed: 'មិនអាចផ្ទុកបញ្ជីអ្នកជំងឺបានទេ',
  chartDetailSearch: 'ស្វែងរកក្នុងបញ្ជី…',
  chartDetailSearchBtn: 'ស្វែងរក',
  chartDetailPage: 'ទំព័រ',
  chartDetailPrev: 'មុន',
  chartDetailNext: 'បន្ទាប់',
  chartDetailOpenProfile: 'ចុច Clinic ID / ART ឬជួរដើម្បីបើកប្រវត្តិអ្នកជំងឺ ៣៦០°',
  chartDetailNoClinicId: 'មិនអាចរកឃើញ Clinic ID សម្រាប់អ្នកជំងឺនេះ',
  chartDetailTabList: 'បញ្ជី',
  chartDetailTabCompare: 'ប្រៀបធៀបរយៈពេល',
  chartCompareWith: 'ប្រៀបធៀបជាមួយ',
  chartCompareNeedTwoPeriods: 'ត្រូវជ្រើសរយៈពេលយ៉ាងហោចណាស់ ២ នៅលើគំនូសតាង (ដំណើរការឡើងវិញជាមួយត្រីមាសច្រើន)',
  chartCompareSamePeriod: 'ជ្រើសរយៈពេលពីរផ្សេងគ្នា',
  chartComparePeriodA: 'រយៈពេល A',
  chartComparePeriodB: 'រយៈពេល B',
  chartCompareRun: 'រកភាពខុសគ្នា',
  chartCompareLoading: 'កំពុងផ្ទុកបញ្ជីពីររយៈពេល…',
  chartCompareDropped: 'បាត់ក្នុង {newer} ({n})',
  chartCompareAdded: 'ថ្មីក្នុង {newer} ({n})',
  chartCompareBoth: 'មានទាំងពីររយៈពេល ({n})',
  chartCompareDroppedHint:
    'បានបញ្ចប់ TPT នៅ {older} ប៉ុន្តែមិននៅក្នុងបញ្ជីបញ្ចប់ {newer} — មូលហេតុតាមស្ថានភាពអ្នកជំងឺ (patientstatus) នៅចុង {newer}',
  chartCompareAddedHint: 'បញ្ចប់ TPT ថ្មីនៅ {newer} (មិនមានក្នុងបញ្ជី {older})',
  chartCompare105At: '10.5 {period}',
  chartComparePatientStatusAt: 'ស្ថានភាព {period}',
  chartComparePatientStatusDateAt: 'កាលបរិច្ឆេទស្ថានភាព {period}',
  chartCompareStatus105Complete: 'TPT Complete (10.5)',
  chartComparePatientStatusActive: 'Active ART',
  chartCompareBothHint: 'មានក្នុងទាំងពីររយៈពេល',
  chartCompareNoOptions: 'គ្មានរយៈពេលផ្សេងដើម្បីប្រៀបធៀប',
  chartCompareNoDiff: 'គ្មានភាពខុសគ្នា — បញ្ជីដូចគ្នា',
  chartCompareSummary: 'A: {a} · B: {b} · បាត់: {removed} · ថ្មី: {added}',
  chartCompareCardDropped: 'បាត់',
  chartCompareCardAdded: 'ថ្មី',
  chartCompareCardDropBreakdown: 'មូលហេតុបាត់',
  chartCompareCardDead: 'ស្លាប់',
  chartCompareCardLtfu: 'LTFU',
  chartCompareCardTransfer: 'ផ្ទេរចេញ',
  chartCompareCardActive: 'Active ART',
  chartCompareCopyTab: 'ចម្លងតារាងនេះ',
  chartCompareCopySuccess: 'បានចម្លងបញ្ជីភាពខុសគ្នា',
  chartCompareReason: 'មូលហេតុ (patientstatus នៅចុងត្រីមាសថ្មី)',
  chartCompareReasonActiveNotIn105: 'នៅ {period} — Active ART (មិននៅក្នុង 10.5)',
  chartCompareReasonPatientStatus: 'នៅ {period} — {status}',
  chartCompareReasonNewComplete: 'បញ្ចប់ TPT ថ្មីនៅ {period} (មុន: {prior})',
  chartCompareReasonSummaryDead: 'ស្លាប់: {n}',
  chartCompareReasonSummaryLtfu: 'LTFU: {n}',
  chartCompareReasonSummaryTransfer: 'ផ្ទេរចេញ: {n}',
  chartCompareReasonSummaryActive: 'Active ART: {n}',
  visualizeRestored: 'បានស្តារលទ្ធផលវិភាគពីមុន',
  facilityOnlyHint: 'សូមជ្រើសរើសកម្រិតមូលដ្ឋានសុខាភិបាល (មិនមែនកម្រិតខេត្ត ឬថ្នាក់ជាតិឡើយ)',
  toastRunFailed: 'មិនអាចដំណើរការទាញយកសូចនាករបានទេ',
  loadingCatalog: 'កំពុងផ្ទុកបញ្ជីសូចនាករ…',
  catalogEmpty: 'មិនមានបញ្ជីសូចនាករទេ — សូមពិនិត្យមើលការតភ្ជាប់ទៅកាន់ម៉ាស៊ីនបម្រើ (Server)'
};